### ISSUE TITLE
Help!!

### ISSUE THREAD

**Issue by GODLIKE5** [iJoshuaHD/ASR#11]
Ummm.... U didnt show how to make this work on android!!!. Android is were most servers are hosted... I think.. well anyways help.. please i need it alot. Thxs

**Comment by wsngamerz** [comment]
ASR is not compatible with android. ASR uses a scrîpt shich when it shuts down it runs a file called start.sh and that file can only be found on a computer and then only on windows OS.
I hope this helped you and others.

**Comment by GODLIKE5** [comment]
@wsngamerz just found out this works with Genisys Android :O

_Sent from my HTC 0PJA2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
