### ISSUE TITLE
Help! Restart script for Mac

### ISSUE THREAD

**Issue by Brandowizard** [iJoshuaHD/ASR#12]
On the documentation link for the restart script there isn't a script for Mac OS. Can someone please create one, add it to the documentation link: https://forums.pocketmine.net/plugins/automatic-server-restarter.903/field?field=documentation along with posting it below. Then help me figure out how to add the restart script to me PocketMine server?

**Comment by iJoshuaHD** [comment]
use the start.sh script. it is the same as Linux.
