### ISSUE TITLE
How to stop server and get rid of minute message.

### ISSUE THREAD

**Issue by Brandowizard** [iJoshuaHD/ASR#13]
I'm sorry that I am posting another help message, I'm a new server owner. I was wondering how to stop the server since I change the NO_LOOP"no" to NO_LOOP"yes". I was also wondering how to remove the message that broadcasts that the server will restart in x minutes. And the message is broadcasted EVERY MINUTE. If there's no way at the moment to remove the message that spams my server, or at least make the length when the message is broadcast longer, please fix it iJoshuaHD. Again, apologies for asking two times in a row for help today. Thanks!

**Comment by iJoshuaHD** [comment]
to stop the server, just use your keyboard and do the combination: ' CTRL + C ' multiple times
as for getting rid of the message, ill try to make an update for that soon when i have time.
