### ISSUE TITLE
annoying PM window

### ISSUE THREAD

**Issue by brainytwoo** [iJoshuaHD/ASR#5]
Good job with the ASR plug in but when my server restarts it leaves the old PM window open i know there is a way to automatically close it but i forgot how could you plz tell me thx. Also how do you turn it off?

**Comment by iJoshuaHD** [comment]
i dont think there is :/ ill try to figure it out though

**Comment by caingaroo** [comment]
Is there anyway that you can modify the plugin were it starts back up the server for people who run there servers on the pocketmine app because win ur not home and your computer runs your server it cant just turn its self back on so can you modify this onto the plugin :/

**Comment by brainytwoo** [comment]
It does turn itself on u just have to follow the instructions on the website ;)

**Comment by caingaroo** [comment]
What about a android device that runs pocketmine can u start it up win ur not around it anyway?

**Comment by brainytwoo** [comment]
Idk I've never messed with the Android stuff
